### ISSUE TITLE
Win Game

### ISSUE THREAD

**Issue by qzcx** [film42/cs340-catan#10]
Winning the game doesn't work. Someone can look into this.

**Comment by ajgoda90** [comment]
Proposed solution: instead of incrementing the victorypoints directly in the "buySettlement" method, instead make a method that increments it based on input and checks to see if it exceeds to declare victory.

Is that acceptable?

**Comment by film42** [comment]
So I did this:

Inside Game:

``` java
    @Override
    public void checkForCompletedGame() {
        for(Player player : players) {
            if(player.getVictoryPoints() >= Catan.MAX_VICTORY_POINTS) {
                setWinner(player.getPlayerID());
            }
        }
    }
```

Inside MoveFacade:

``` java
        // Run this command then return OK
        command.execute(game);

        // Test game for winner
        game.getData().checkForCompletedGame();
```

No matter what the command is, it will always update the winning ID.

**Comment by ajgoda90** [comment]
I found an error in the javascript of PointsController.js. I'm not sure if that was there already and we somehow missed it?
