### ISSUE TITLE
Potential Bug: Dev Card Modal Cannot be Opened After Using a Dev Card

### ISSUE THREAD

**Issue by film42** [film42/cs340-catan#18]
Just closes and turns disabled. Good? Bad?

**Comment by ajgoda90** [comment]
Seems like a client thing. I think you shouldn't be able to use more than one dev card per turn

**Comment by todoakaio** [comment]
Yeah I think while it's not technically wrong, it could be a bug logged against us.  I think it's fine as is, however.  If it gets logged then I guess we can look into it further.

**Comment by todoakaio** [comment]
We asked the T.A.'s (Jon) and he said this is ok functionality.

**Comment by todoakaio** [comment]
Marked as wontfix because while we could fix it, it isn't a do or die fix.
