### ISSUE TITLE
Map Problems

### ISSUE THREAD

**Issue by film42** [film42/cs340-catan#2]
Hey @ajgoda90 , here's your nice clean report.
## Drawing city and board weird after upgrade

Proof: <img src="http://desh.es/s/144559.png">
## Can Build City

I'm passing correct values into Map.canBuildCity()

_Params:_
HexLocation: <img src="http://desh.es/s/143615.png">
PlayerID: 0
Dir: "E"

but... this.hexGrid.getVertex(hexLoc, dir); returns null
## Building a settlement at the end of a road on the shore

Your'e ruining my game.

Found a bug for you.

Here's a very good screenshot:
<img src="http://desh.es/s/141959.png">

**Comment by film42** [comment]
I have a feeling a lot of these are related.

**Comment by ajgoda90** [comment]
1st problem is the buildCity on proxy was sending xy coordinates with yy values.

2nd problem, null should be returned. canBuildCity was not properly checking for it.

3rd problem. My getEdgesFromVertex wasn't returning the proper edges...this is the second time I've had this issue from hexgrid. I guess phase 1 testing was insufficient.
