### ISSUE TITLE
Starting resources

### ISSUE THREAD

**Issue by qzcx** [film42/cs340-catan#21]
Sometimes starting resources doesn't give you correct resources
![screen shot 2014-03-25 at 2 27 13 pm](https://f.cloud.github.com/assets/6502268/2517699/e08feaaa-b45b-11e3-939b-a041728c11bb.png)

**Comment by todoakaio** [comment]
Who is the user at this point?  The green?

**Comment by qzcx** [comment]
yeah green. and the second settlement is the one between the two brick and the wood.

**Comment by ajgoda90** [comment]
Instead of incrementing for each instance of a resource hex, it was setting it to one. Fixed.
