### ISSUE TITLE
problems with bank

### ISSUE THREAD

**Issue by qzcx** [film42/cs340-catan#23]
I'm seeing some problems with bank like 
bank: {
brick: 50,
wood: 27,
sheep: 6,
wheat: 8,
ore: 0
},
So not all the ore is in the players hands, so it disappeared. We just need to go over all of the returning cards to the bank functions to ensure they get back. This is why I couldn't trade for ore before.

**Comment by todoakaio** [comment]
Pretty sure Jon fixed this in c84baf3492808f7bf6014cc4d6505e69a11489d6
