### ISSUE TITLE
Domestic Trading

### ISSUE THREAD

**Issue by qzcx** [film42/cs340-catan#26]
You should be able to send more than one resource at a time for more than one resource of another type. For example I should be able to send 1 wood and 1 sheep for 1 brick. Currently if I select to give 1 wood and then click send on sheep, then it will unselect wood.

**Comment by todoakaio** [comment]
https://code.google.com/p/byu-cs340-winter14-catan/issues/detail?id=77
This has been previously verified as an invalid bug (though it may change in future semesters)
