### ISSUE TITLE
No game or proxy interface to /moves/robPlayer

### ISSUE THREAD

**Issue by ajgoda90** [film42/cs340-catan#3]
This is a needed function that appears in the example Server REST json that they provide on the project page of the class website. For some reason the server does not return the exact same json for the api, so it doesn't appear in the REST tester. Below is the json from the example for the /moves/robPlayer command. The server will have to be checked to see if it does in fact respond to this...if it doesn't then we should protest...

```
{
        "args": [],
        "url": "/moves/robPlayer",
        "method": "POST",
        "description": "Moves the robber, selecting the new robber position and player to rob.",
        "type": "JSON",
        "template": {
            "type": "robPlayer",
            "playerIndex": -1,
            "victimIndex": -1,
            "location": {
                "x": "",
                "y": ""
            }
        }
    },
```

**Comment by film42** [comment]
Would you like me to add it right now?

**Comment by ajgoda90** [comment]
If you can, that'd be helpful. I'm right there at needing to call it

**Comment by film42** [comment]
Ok, I'll get it done.

**Comment by film42** [comment]
Nearly done.. I'm adding it to game now.

Question about checking before using:

``` javascript
  Game.prototype.robPlayer = function(victimId, location, callback) {
    callback = callback || function() {};

    var playerId = this.getCurrentPlayerOrder();
    var canPlaySoldier = this.model.canPlaySoldier(victimId, location);

    if(!canPlaySoldier) return callback({error: "Cannot Rob Player!"});

    this.proxy.robPlayer(playerId, victimId, location, callback);
  };
```

Should I be checking if it can play a soldier card? Or should I just send it straight to the proxy?

**Comment by ajgoda90** [comment]
No. This is for when a 7 is rolled, not for when a soldier card is played. We already have a method for that. We should probably add another can to see if someone can be robbed from a specific location though...

**Comment by ajgoda90** [comment]
But that seems unnecessary to actually move forward with this.

**Comment by ajgoda90** [comment]
Oh, we have that its called canPlayRobber in the client model. It takes the same as the canPlaySoldier method

**Comment by film42** [comment]
Pushed and added a test case to ensure the proxy part is working.

It's now basically identical to how `playSoldier` works.

**Comment by ajgoda90** [comment]
Well, I fixed a couple of bugs it ran until it updated from server again. Then there was no robber object returned, so map fails to serialize. Server bug?

**Comment by ajgoda90** [comment]
Seems to be working. Other robber bugs have issues
